# Site settings
author: PHILLIP OJO
title: Module 1 Project
header-img: img/home-bg.png
email: phillipojo24@gmail.com
copyright_name: PHILLIP OJO
description: > # this means to ignore newlines until "baseurl:"
  draft
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  phillipojo24

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
